package weixin.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-05T15:16:40.513+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "MyWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/trade/service/myservice?wsdl",
                  targetNamespace = "http://impl.webservice.com/") 
public class MyWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.com/", "MyWebServiceImplService");
    public final static QName Meport = new QName("http://impl.webservice.com/", "meport");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/trade/service/myservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/trade/service/myservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MyWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "meport")
    public MyWebService getMeport() {
        return super.getPort(Meport, MyWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebService
     */
    @WebEndpoint(name = "meport")
    public MyWebService getMeport(WebServiceFeature... features) {
        return super.getPort(Meport, MyWebService.class, features);
    }

}
